### ISSUE TITLE
Visual Studio integration

### ISSUE THREAD

**Issue by andrewdavey** [fdecampredon/jsx-typescript#3]
I'm very excited to see this fork. I've been waiting to use React in TypeScript for ages :smile: So thank you for making it happen!

Is Visual Studio integration on the roadmap? Whilst I'm happy to use the command line compiler to build, editing TS files containing JSX in VS results in red squiggles. I can live without full blown highlighting of JSX, as long as it's not showing as errors.

Is there any way to hack/replace the typescript compiler used by VS and use jsx-typescript instead?

**Comment by fdecampredon** [comment]
@andrewdavey I tried to respect the language service api the most I could, also I don't update from master since the current version seems to be the last one supporting visual studio. (the current visual studio version)

I know there is a way to use a custom compiler in visual studio did you try that ?

**Comment by andrewdavey** [comment]
It looks like maybe I can replace the installed typescript files used by VS: https://github.com/Microsoft/TypeScript/issues/1110#issuecomment-62451204

I'll have to have a hack and report back.

**Comment by fdecampredon** [comment]
see also https://github.com/Microsoft/TypeScript/wiki/Dev-Mode-in-Visual-Studio

jsx-typescript works with my own editor that use the same api than visual studio, if there is a bug in vs let me know ;)

**Comment by andrewdavey** [comment]
Thanks for that link. Setting the registry key
`HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\12.0\TypeScriptLanguageService` to `c:\path\to\jsx-typescript\bin\typescriptServices.js` works.

**Comment by fdecampredon** [comment]
cool to hear that except for formatting everything should be fine feel free to submit bug if they are
